name: Auto_Helper

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "23 2 * * *" # 该时间为UTC时间，比北京时间晚8个小时，每天早上5点半自动执行

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci

  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Run Project
        env:
          COOKIE: ${{ secrets.COOKIE }}
          COOKIE2: ${{ secrets.COOKIE2 }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          TO: ${{ secrets.TO }}
          YUN_COOKIE: ${{ secrets.YUN_COOKIE }}
          YUN_TO: ${{secrets.YUN_TO}}
        run: npm ci && node src/juejin.js "${COOKIE}" "${USER}" "${PASS}" "${TO}" "${YUN_COOKIE}" "${YUN_TO}"  npm ci && node src/v2free.js "${COOKIE2}" "${USER}" "${PASS}" "${TO}"
